version: '3'

services:
    shlink_nginx:
        image: nginx:1.19.6-alpine
        ports:
            - "172.17.0.1:8734:80"
        volumes:
            - ./nginx/:/etc/nginx/conf.d/:ro

    shlink_db_mysql:
      image: mysql:latest
      restart: always
      environment:
        - MYSQL_DATABASE=shlink
        - MYSQL_PASSWORD=${ADMIN_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
      volumes:
        - ./data/infra/database:/var/lib/mysql
  
    shlink_app:
      image: shlinkio/shlink:${SOFTWARE_VERSION_TAG}
      ports:
        - "172.17.0.1:8080:8080"
      environment:
        - DEFAULT_DOMAIN=${DOMAIN}
        - IS_HTTPS_ENABLED=true
        - DB_DRIVER=mysql
        - DB_USER=root
        - DB_PASSWORD=${ADMIN_PASSWORD}
        - DB_HOST=shlink_db_mysql
        - DB_PORT=3306 
      restart: always
      depends_on:
        - shlink_db_mysql

    shlink_web_client:
      image: shlinkio/shlink-web-client:${SOFTWARE_VERSION_TAG}
      restart: always
      ports:
        - "172.17.0.1:8081:80"
      environment:
        - SHLINK_SERVER_URL=https://${DOMAIN}
        - SHLINK_SERVER_NAME=Main server
        - SHLINK_SERVER_API_KEY=
